const tracks = [
  {
    id: 1,
    name: 'Guilt',
    author: 'Nero',
    release_date: '2005-06-11',
    genre: 'Техно',
    duration_in_seconds: 284,
    album: 'Welcome Reality',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 2,
    name: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    release_date: '2010-06-11',
    genre: 'Инди',
    duration_in_seconds: 352,
    album: 'Elektro',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 3,
    name: 'I’m Fire',
    author: 'Ali Bakgor',
    release_date: '2015-06-11',
    genre: 'Техно',
    duration_in_seconds: 234,
    album: 'I’m Fire',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 4,
    name: 'Non Stop',
    author: 'Стоункат, Psychopath',
    release_date: '1988-06-11',
    genre: 'Рок',
    duration_in_seconds: 123,
    album: 'Non Stop',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 5,
    name: 'Run Run',
    author: 'Jaded, Will Clarke, AR/CO',
    release_date: '2000-06-11',
    genre: 'Хип-хоп',
    duration_in_seconds: 321,
    album: 'Run Run',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 6,
    name: 'Eyes on Fire',
    author: 'Blue Foundation, Zeds Dead ',
    release_date: '2001-06-11',
    genre: 'Рок',
    duration_in_seconds: 213,
    album: 'Welcome Reality',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 7,
    name: 'Mucho Bien',
    author: 'HYBIT, Mr. Black, Offer Nissim, Hi Profile',
    release_date: '1995-06-11',
    genre: 'Инди',
    duration_in_seconds: 231,
    album: 'Mucho Bien',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 8,
    name: 'Knives n Cherries',
    author: 'minthaze',
    release_date: '2022-06-11',
    genre: 'Инди',
    duration_in_seconds: 345,
    album: 'Captivating',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 9,
    name: 'How Deep Is Your Love',
    author: 'Calvin Harris, Disciples',
    release_date: '2001-06-11',
    genre: 'Инди',
    duration_in_seconds: 456,
    album: 'How Deep Is Your Love',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
];

export default tracks;
